### ISSUE TITLE
Clarification about the data licence - CC BY-NC-SA 4.0 or not

### ISSUE THREAD

**Issue by tvercaut** [fepegar/SlicerEPISURG#1]
Thanks for sharing this work. Not sure if this is the best place to ask questions about the dataset but I thought GitHub would be an easier reference for others than private emails.

Looking at the EpiSurg dataset I can see the custom "Data use agreement" but the landing page also has a "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)" badge as shown below: 
https://doi.org/10.5522/04/9996158.v1

The README in the zip file refers to the "Data use agreement" but doesn't mention CC BY-NC-SA 4.0 or any other restriction.

Could you clarify if CC BY-NC-SA 4.0 applies and if not maybe ask UCL to remove the badge?

![Screenshot 2022-08-25 at 19 01 26](https://user-images.githubusercontent.com/1614505/186726087-34dfc584-1892-4429-a91d-df9aee9fe28a.png)

**Comment by fepegar** [comment]
Hi, @tvercaut. Sorry for the delay, I've been on holiday. I will investigate this and get back to you. Are you interested in using the dataset?

**Comment by fepegar** [comment]
@rsparks could you please look into this?

**Comment by fepegar** [comment]
Maybe @HChughtai could also provide some advice.

**Comment by HChughtai** [comment]
Hi @fepegar - not the remit of the team I'm part of, but I believe that license is chosen by the uploaders when they create an entry on the [UCL Research Data Repository](https://www.ucl.ac.uk/library/open-science-research-support/research-data-management/ucl-research-data-repository). You may want to contact the helpdesk email address on that page for clarification and for modification if you can't do so yourself directly.

**Comment by tvercaut** [comment]
Thanks @fepegar, yes we have been discussing about using this dataset with Rachel and @aaronkujawa. I just need to make sure it won't be a problem in terms of licensing.

**Comment by tvercaut** [comment]
@fepegar @rsparks : Would you have any update on this issue?

**Comment by res191** [comment]
@tvercaut, sorry for the delay in response I am not @rsparks on here so did not receive the original query. I am afraid this dataset is currently available only for non-commercial purposes so the CC-BY-NC-SA-4.0 does apply. Happy to have a more detailed conversation to potentially seek a more permissive license if you would like to use this for commercial purposes.

**Comment by fepegar** [comment]
Oops. Sorry, Rachel!

**Comment by tvercaut** [comment]
Thanks Rachel. I would suggest clarifying this on the landing page under "Data use agreement" and also highlight this in the zipped dataset itself. The option of a permissive licence would of course be interesting. I'll catch-up offline on this.
